@echo off
echo Starting API Gateway...
start "API Gateway" cmd /k "cd apps\api-gateway && node dist/main.js"

echo Starting Products Service...
start "Products Service" cmd /k "cd apps\products-service && node dist/main.js"

echo Starting Orders Service...
start "Orders Service" cmd /k "cd apps\orders-service && node dist/main.js"

echo All services starting...
pause
